### PR TITLE
major/feature/UBI-360-integration-tests-in-parallel

### PR DESCRIPTION
**Pull request by ArcticWalrus**
#### What changes does this PR contain?
Integration tests and splits build from test steps
#### Which JIRA ticket ID's are associated with this PR?
UBI-360

### CODE REVIEW

**Comment by ArcticWalrus** [comment]
@ysma500 Do we want the publish docker and helm in pr-dev to be able to test our prs in the future?

**Review by JeremiSavard — APPROVED** [review]

**Comment by ArcticWalrus** [comment]
One more thing @ysma500 
This repository seems to be quite a bit behind the microservices. Were a bunch of changes brought over by hand?

**Comment by ArcticWalrus** [comment]
@ysma500 Good to go for the review

**Review by ysma500 — APPROVED** [review]
LGTM

**Pull request merged**
